// <auto-generated />
namespace Cer.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changes071216052016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes071216052016));
        
        string IMigrationMetadata.Id
        {
            get { return "201605160418422_changes071216052016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
