// <auto-generated />
namespace Cer.Infrastructure.Data.EfProvider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial20160523 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial20160523));
        
        string IMigrationMetadata.Id
        {
            get { return "201605230611225_initial20160523"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
