// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Cer.Infrastructure.Data.EfProvider.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initalDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initalDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201605141619025_initalDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
